let Sequence = require('./index')
//
let ar = [0,1,2,3,4,5,6,7,8]
console.log(ar)

let sequence = new Sequence( ar )
console.log( sequence.currentItem )
sequence.next()
console.log( sequence.currentItem )
sequence.next()
console.log( sequence.currentItem )
sequence.next()
console.log( sequence.currentItem )
sequence.next()
console.log( sequence.currentItem )
sequence.next()
console.log( sequence.currentItem )
sequence.next()
console.log( sequence.currentItem )
sequence.next()
console.log( sequence.currentItem )
sequence.next()
console.log( sequence.currentItem )
sequence.next()
console.log( sequence.currentItem )
sequence.next(true)
console.log( sequence.currentItem )
sequence.next()
console.log( sequence.currentItem )
sequence.prev()
console.log( sequence.currentItem )
