let Sequence = require('./index')
//
let ar = [0,1,2,3,4,5,6,7,8]
console.log(ar)

let sequence = new Sequence( ar )
console.log( 'list:' )
console.log( ar )
console.log( "First Item" )
console.log( sequence.firstItem )
console.log( "Last Item" )
console.log( sequence.lastItem )
console.log( sequence.currentItem )
console.log("next()")
sequence.next()
console.log( sequence.currentItem )
console.log("next()")
sequence.next()
console.log( sequence.currentItem )
console.log("next()")
sequence.next()
console.log( sequence.currentItem )
console.log("next()")
sequence.next()
console.log( sequence.currentItem )
console.log("next()")
sequence.next()
console.log( sequence.currentItem )
console.log("next()")
sequence.next()
console.log( sequence.currentItem )
console.log("next()")
sequence.next()
console.log( sequence.currentItem )
console.log("next()")
sequence.next()
console.log( sequence.currentItem )
console.log("next()")
sequence.next()
console.log( sequence.currentItem )
console.log("next(true) # loops back to start on overshoot" )
sequence.next(true)
console.log( sequence.currentItem )
console.log("next()")
sequence.next()
console.log( sequence.currentItem )
console.log("prev()")
sequence.prev()
console.log( sequence.currentItem )
